remote_theme: hydecorp/hydejack
plugins:
  - jekyll-remote-theme

# Setup
title: 前额叶工坊
description: 探究生活，记录感悟
url: https://cantblues.github.io
avatar: /avatar.jpg
paginate: 10
permalink: pretty
cover_image: /bg.jpeg

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec

# Optimize Jekyl SEO Tag
twitter:
  username: CantBlues
  card: summary
logo: logo.png
social:
  name: CantBlues
  links:
    - https://twitter.com/cant_blues
    - https://github.com/CantBlues
google_site_verification: Hax0qorb4nJv0QfMcxzF_qHi-SkyL3hiXIYRq7k6xvI
google_analytics: G-V9TWSWZMKC
lang: zh-cn

sass:
  sass_dir: _sass
  style: :compressed


# Replace this value and uncomment to enable Disqus
# disqus: xxxxxx

author:
  name: 蓝不住
  url: https://cantblues.github.io
  email: wyslanbin@gmail.com
