remote_theme: CantBlues/hydejack
plugins:
  - jekyll-remote-theme

# Setup
title: 前额叶工坊
logo: avatar.jpg
description: 探究生活，记录感悟

paginate: 10
paginate_path: '/:num/'

theme_color:  rgb(204,204,204)
accent_image: /background.jpg
accent_color: rgb(204,204,204)

menu: 
  - title: Life 
    url: /life/
  - title: Movie
    url: /movie/
  - title: Tech
    url: /tech/
  - title: Wechat
    url: /wechat/

collections:
  featured_categories:
    permalink:         /:name/
    output:            true
  featured_tags:
    permalink:         /tag-:name/
    output:            true
# Gems
plugins: 
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
 
google_site_verification: Hax0qorb4nJv0QfMcxzF_qHi-SkyL3hiXIYRq7k6xvI
google_analytics: G-V9TWSWZMKC
lang: zh-cn

defaults:
  - scope:
      type: posts
    values:
      comments: true

disqus: cantblues

author:
  name: 蓝不住
  social: 
    email: wyslanbin@gmail.com
    twitter: cant_blues
    github: CantBlues

legal:
  - title: Comment Policy
    url:  /comment_policy/
